---
# path to conda on my own machine (adapt for yours)
condapath: "/opt/biotools/miniconda3/condabin"
condaenv: "InSilico_PCR"

# url for raw data
host: "https://nanopore.s3.climb.ac.uk/"
infile: "Zymo-PromethION-EVEN-BB-SN.fq.gz"

# extract reads corresponding to the 16S PCR
forwardp:"AGAGTTTGATCMTGGCTCAG"
reversep:"CGGTWACCTTGTTACGACTT"

# result folder names
split="split_data"
tmpout="bbmap_out"

# split data in 500k read bins (500000x4=2000000)
lines:2000000

# threads for parallel tasks
thr:80

# threads for compression
pigt:8

# max mem for BBMap tasks
mem:"8g"

# stringent primer finding to avoid noisy reads
cut:0.8

# exclude the 1% shortest reads, change to 0 to disable filtering
filterperc=0.01
