---
# path to conda on the machine
condapath: "/opt/biotools/miniconda3/condabin"
condaenv: "InSilico_PCR"

# url for raw data
infile: "Zymo-PromethION-EVEN-BB-SN.fq.gz"
url: "https://nanopore.s3.climb.ac.uk/"[infile]

# extract reads corresponding to the 16S PCR
forwardp: "AGAGTTTGATCMTGGCTCAG"
reversep: "CGGTWACCTTGTTACGACTT"

# result folder names
split: "split_data"
tmpout: "bbmap_out"

# split data in 500k read bins
lines: 2000000

# threads for parallel tasks
thr: 48

# threads for compression
pigt: 8

# max mem for BBMap tasks
mem: "8g"

# stringent primer finding to avoid noisy reads
cut: 0.8

# minimum expected amplicon length for final filtering and merging
minl: 1000
